### PR TITLE
[admin] Styling active_admin to UPeC

### PR DESCRIPTION
**Pull request by andreslucena**

### CODE REVIEW

**Review by deivid-rodriguez — COMMENTED** [review]
Is the Comuns_Logo.png image needed? I guess it's not for this PR, but we might add it to the emails to try fix the problems displaying the current logo in the emails?

**Comment by andreslucena** [comment]
Exactly, that was the idea. It doesn't below to this PR :(

**Comment by andreslucena** [comment]
At the moment we're gonna merge this, on the future we'll add the link to the mail layout.

**Comment by deivid-rodriguez** [comment]
:+1:

**Pull request merged**
