### PR TITLE
Remove overrides

### LINKED ISSUE #54: Remove vendor/overrides
We're not using the overrides model for the most part. We need to delete it and migrate it to the general app/ folder. Also we need to remove it from config/application.rb

For improving the reuse with another projects, we should study this https://github.com/chamnap/themes_on_rails

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
Partially fixes #54. Still some translations left to be merged, but it's a start.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
@andreslucena Getting old PR's in. Want to review this? If you have no time, I'll just self-merge tomorrow! :wink:

**Comment by andreslucena** [comment]
@deivid-rodriguez can we try to use themes_on_rails or similar to at least use the same codebase between BeC and UPeC? Or maybe that's too much work?

**Comment by deivid-rodriguez** [comment]
Hi Andrés, I'm not sure how much work that would be, but I still don't know how that helps here.

I think we could use something like that if we chose a "monorepository" solution, but we seem to prefer the "forking" approach, so I don't see how adding this gem would help us. The proper solution for code sharing from multiple repos in this case would be to build an engine that you can plug into any app like they did in https://github.com/AjuntamentdeBarcelona/decidim.

I think the situation is a bit different here though. Whereas `Consul` received a very big amount of contributions making it a problem to "pick them up", participa.info & BeC's participa are very inactive repositories, so code sharing feels like less of a problem.

**Comment by andreslucena** [comment]
Ok, that's fine by me.

For the moment the only development doing on this repositories are OAUTH2 with UserGroups for BeC. For UPeC at the moment there aren't plans to using this new feature.

**Comment by deivid-rodriguez** [comment]
:+1: If we wanted to use those features I can cherry-pick them manually.

**Pull request merged**
